`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 07/20/2023 11:29:46 PM
// Design Name: 
// Module Name: qpsk
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

// -------------------------------------------------------------
// 
// File Name: hdlsrc/qpsk1/qpsk1.v
// Created: 2023-07-17 17:49:33
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: qpsk1
// Source Path: qpsk1
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module qpsk1
          (clk,
           reset,
           clk_enable,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  ce_out;
  output  [7:0] Out1;  // uint8


  wire enb;
  wire [15:0] count_step;  // uint16
  reg [15:0] Counter_Free_Running_out1;  // uint16
  wire [15:0] count;  // uint16
  wire signed [15:0] QPSK_Modulator_Baseband_out1_re;  // sfix16_En15
  wire signed [15:0] QPSK_Modulator_Baseband_out1_im;  // sfix16_En15
  wire [7:0] QPSK_Demodulator_Baseband_out1;  // uint8


  assign count_step = 16'b0000000000000001;



  assign enb = clk_enable;

  assign count = Counter_Free_Running_out1 + count_step;



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : Counter_Free_Running_process
      if (reset == 1'b1) begin
        Counter_Free_Running_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Counter_Free_Running_out1 <= count;
        end
      end
    end



  QPSK_Modulator_Baseband u_QPSK_Modulator_Baseband (.in0(Counter_Free_Running_out1),  // uint16
                                                     .out0_re(QPSK_Modulator_Baseband_out1_re),  // sfix16_En15
                                                     .out0_im(QPSK_Modulator_Baseband_out1_im)  // sfix16_En15
                                                     );

  QPSK_Demodulator_Baseband u_QPSK_Demodulator_Baseband (.in0_re(QPSK_Modulator_Baseband_out1_re),  // sfix16_En15
                                                         .in0_im(QPSK_Modulator_Baseband_out1_im),  // sfix16_En15
                                                         .out0(QPSK_Demodulator_Baseband_out1)  // uint8
                                                         );

  assign Out1 = QPSK_Demodulator_Baseband_out1;

  assign ce_out = clk_enable;

endmodule  // qpsk1
