`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 07/20/2023 11:45:54 PM
// Design Name: 
// Module Name: qpskdemodul
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////



// -------------------------------------------------------------
// 
// File Name: hdlsrc/qpsk1/QPSK_Demodulator_Baseband.v
// Created: 2023-07-20 18:13:57
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: QPSK_Demodulator_Baseband
// Source Path: qpsk1/QPSK Demodulator Baseband
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module QPSK_Demodulator_Baseband
          (in0_re,
           in0_im,
           out0);


  input   signed [15:0] in0_re;  // sfix16_En15
  input   signed [15:0] in0_im;  // sfix16_En15
  output  [7:0] out0;  // uint8


  wire inphase_lt_zero;
  wire inphase_eq_zero;
  wire quadrature_lt_zero;
  wire quadrature_eq_zero;
  wire [3:0] decisionLUTaddr;  // ufix4
  wire [1:0] DirectLookupTable_1 [0:15];  // ufix2 [16]
  wire [1:0] hardDecision;  // ufix2


  assign inphase_lt_zero = in0_re < 16'sb0000000000000000;



  assign inphase_eq_zero = in0_re == 16'sb0000000000000000;



  assign quadrature_lt_zero = in0_im < 16'sb0000000000000000;



  assign quadrature_eq_zero = in0_im == 16'sb0000000000000000;



  assign decisionLUTaddr = {inphase_lt_zero, inphase_eq_zero, quadrature_lt_zero, quadrature_eq_zero};



  assign DirectLookupTable_1[0] = 2'b00;
  assign DirectLookupTable_1[1] = 2'b00;
  assign DirectLookupTable_1[2] = 2'b10;
  assign DirectLookupTable_1[3] = 2'b00;
  assign DirectLookupTable_1[4] = 2'b01;
  assign DirectLookupTable_1[5] = 2'b00;
  assign DirectLookupTable_1[6] = 2'b10;
  assign DirectLookupTable_1[7] = 2'b00;
  assign DirectLookupTable_1[8] = 2'b01;
  assign DirectLookupTable_1[9] = 2'b11;
  assign DirectLookupTable_1[10] = 2'b11;
  assign DirectLookupTable_1[11] = 2'b00;
  assign DirectLookupTable_1[12] = 2'b00;
  assign DirectLookupTable_1[13] = 2'b00;
  assign DirectLookupTable_1[14] = 2'b00;
  assign DirectLookupTable_1[15] = 2'b00;
  assign hardDecision = DirectLookupTable_1[decisionLUTaddr];



  assign out0 = {6'b0, hardDecision};



endmodule  // QPSK_Demodulator_Baseband


