`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 07/20/2023 11:30:36 PM
// Design Name: 
// Module Name: qpskmodul
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


// -------------------------------------------------------------
// 
// File Name: hdlsrc/qpsk1/QPSK_Modulator_Baseband.v
// Created: 2023-07-20 18:13:57
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: QPSK_Modulator_Baseband
// Source Path: qpsk1/QPSK Modulator Baseband
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module QPSK_Modulator_Baseband
          (in0,
           out0_re,
           out0_im);


  input   [15:0] in0;  // uint16
  output  signed [15:0] out0_re;  // sfix16_En15
  output  signed [15:0] out0_im;  // sfix16_En15


  wire [1:0] constellationLUTaddress;  // ufix2
  wire signed [15:0] constellationLUT_t1_re [0:3];  // sfix16_En15 [4]
  wire signed [15:0] constellationLUT_t1_im [0:3];  // sfix16_En15 [4]


  assign constellationLUTaddress = in0[1:0];



  assign constellationLUT_t1_re[0] = 16'sb0101101010000010;
  assign constellationLUT_t1_re[1] = 16'sb1010010101111110;
  assign constellationLUT_t1_re[2] = 16'sb0101101010000010;
  assign constellationLUT_t1_re[3] = 16'sb1010010101111110;
  assign constellationLUT_t1_im[0] = 16'sb0101101010000010;
  assign constellationLUT_t1_im[1] = 16'sb0101101010000010;
  assign constellationLUT_t1_im[2] = 16'sb1010010101111110;
  assign constellationLUT_t1_im[3] = 16'sb1010010101111110;
  assign out0_re = constellationLUT_t1_re[constellationLUTaddress];
  assign out0_im = constellationLUT_t1_im[constellationLUTaddress];



endmodule  // QPSK_Modulator_Baseband

